### ISSUE TITLE
GABRIELLE ZANDI - Class 2 (3/30)

### ISSUE THREAD

**Issue by gzandi** [Adamor/FEWD3.28#10]
https://github.com/gzandi/FEWD328_GABI/commit/cf258f1682b786495f2bff750f453fb3204bd072

**Comfort:** 4
**Completeness:** 4 (or 5?)
**Wins:** Overall practicing and learning more HTML and CSS 
**Challenges:** 

- Formatting the resume list items with external style sheets

- Figuring out how to properly format the picture within the text on the about page

- Knowing if I am using the right HTML tags for each element 

**Other comments:** 

Enjoyed the assignment - thought it was good to figure things out on our own (and was grateful for the resources sent out!)

_Note: I put completeness as a 4, because I just wasn't sure if my padding, margins, font, etc. are all correct, otherwise I feel like I completed the assignment._

**Comment by heyyy-sebastian** [comment]
Hi Gabi -

This is excellent! Really nice work. 

Insofar as padding/margins/font sizing etc goes for compeltion, yours looks great. A lot of times when you're working from a mock-up as a web designer, a client will explicitly specify the spacing/sizing to use, so approximately this mock-up is totally fine, considering we didn't give you a scale to work with. The appearance is clean and legible and visually appealing, and that's what matters here.

Image positioning is difficult, and a lot of people who have turned in their homework have had the same issue, but yours looks good; you're using float correctly, but the only thing I would say is that your img doesn't need to be embedded in the paragraph tag -- you could pull it out to be above the p tag and the text should still flow around it because you have floats specified.

Knowing which HTML tags to use is something that comes with practice; the only change I would make to your HTML file would be to update the link tags to an unordered list. This is more semantic, since you're listing links to different sites/pages. If you want all of these links to have the same font-size, I would recommend setting it in the CSS rather than wrapping all the items in an h4 tag. Header tags in general denote a single headline/title/subtitle rather than a collection of links.

Awesome job!!! 💯

**Comment by gzandi** [comment]
Thank you for your thorough feedback, I really appreciate it!
