### ISSUE TITLE
Michelle Hsu 04.04

### ISSUE THREAD

**Issue by michellehsu** [Adamor/FEWD3.28#11]
Write Section:
Link to assignment: https://github.com/michellehsu/FEWD3.30.git

Comfort: 5
Completeness: 5
Wins/Challenges: wins! CSS selectors!!

**Comment by heyyy-sebastian** [comment]
Hi Michelle - 

This looks amazing! Really nice work - definitely the cleanest code I've seen so far.

The only feedback I have is that you might want to look at the mockups again to see if you could update the colors on About Me/Resume and footer links to match, and bold the schools in the education section. Everything else looks great, and your code is awesome; I only bring up those two tiny things because because if you're a web designer, clients can definitely get nit-picky about details. Otherwise, awesome job! 💯
