### ISSUE TITLE
Stephanie Willhide - Class 2 (3.30)

### ISSUE THREAD

**Issue by stephaniewillhide** [Adamor/FEWD3.28#14]
https://github.com/stephaniewillhide/FEWD328_stephanie/commit/2319ed0c542459125252e12ccbee610c3e6ea274

Comfort: 3
Completeness: 4

Wins: I learned some new things about CSS

Challenges: I initially had my links in the header and footer in an unordered list, then a span, then I finally settled on a paragraph tag, which I am not sure is ideal. I created the CSS file to suit index.html, but then realized that things would not work correctly in my other file, so I went back and redid a lot. I know that I could be doing a lot of this much more efficiently.

The active link isn't coming up quite right, and I think that some formatting could use some tweaking to look more like the image.

**Comment by heyyy-sebastian** [comment]
Hi Stephanie -

First off, this looks SO good! I know at first building things out can feel like a lot of work that ends up getting scrapped, but trial and error is definitely the rule and not the exception for programming in general, so I hope you see that you've built something really nice.

A few things about your code/questions:
- Your first instinct to put the link tags in an unordered list was correct. An UL is more semantic than a paragraph tag because you're making a list of links, rather than marking up a continuous block of text. Otherwise, your use of HTML tags is excellent.
- You can define the size of your img.headshot in your CSS file -- it's best to put all your styling in one place because it's easier to keep track of; I would also consider moving it down underneath the h3 tag because it's part of the content that goes under that headline.
- For your active links, I would try seeing if you need to creator a compound selector for these tags (i.e. `ul li a {style goes here}`). It's possible the styling isn't being applied because it needs to latch on to the parent selector(s) before it gets to the <a> tags.
- Overall, this reflects the  mockup well. The only thing I would say about the formatting would be to narrow the content sections a bit. Usually the content of the main container is around 60-80% of the page width, but it depends on how big your screen size is as well -- basically you're trying to create the optimal number of words per line for reading comprehension. It probably varies from language to language, but there's some interesting science behind it: http://webstyleguide.com/wsg3/7-page-design/6-page-width-line-length.html Besides that, I honestly have nothing else to critique about your formatting.

Great work! 🎉
