### ISSUE TITLE
Christine Purdy - Class 2 (3.30)

### ISSUE THREAD

**Issue by czpurdy** [Adamor/FEWD3.28#16]
https://github.com/czpurdy/FEWD328_CHRISTINE/commit/9d30187f7ff43c2ce90c305c338aba0fd0895d7a

Comfort: 3.5
Completeness: 4

Wins: I have a better understanding of when to use certain tags and am getting more used to coding in general. I'm definitely starting to think a bit more about the structure before going in (partly because I have a better understanding of how things work now). I was excited that I knew how to accomplish some of what I wanted in a number of ways. I was able to spend some time considering which option would be the best in this context.

Challenges: While I definitely understand all of this a bit more, I'm still not fluent enough to really focus on organizing all of my code. I was hoping to have time to review and clean up my code more before turning this in, but I still wasn't able to figure out why the sizing is so different from one page to another. This definitely could have been a bit more efficient, but I got closer to the original than I was expecting to based on my progress yesterday/earlier in the week!

One other thing that was frustrating was the way the images appear on the screen, but I know that's a larger issue in general (and possibly less a me issue? At least less so than the other issues I experienced!)

**Comment by heyyy-sebastian** [comment]
Hi Christine - 

This looks really good! Regardless of how much you think you did (or didn't) clean up your code, you've built a really nice site that reflects the mock-up almost perfectly and has clean code. The kind of fluency you're talking about will come with practice, so you're in a really good spot. Thinking about your structure is definitely helpful before coding anything -- I routinely sketch out my page layouts before I type anything on a screen, much like making an outline for a paper.

A few minor tweaks:
- I would look at the selector you’re using for the active pseudo element for the anchor tags. The italic font style might not be sticking because you need to point to the parent element in a compound selector (i.e. `ul li a {try some styling here}`).
- I would try embedding the image in your article tag, since the image is part of the content that’s included under your headers. This will probably help push the links at the bottom down a bit, too. Hopefully covering floats in class last week helped clarify how to position images with the text flowing around it, but here's a short how-to as another good reference: https://css-tricks.com/all-about-floats/ 
- You want to wrap your link tags in an unordered list -it’s more semantic that way because you're making a list of links, rather than leaving the <a> tags floating (this will also work with the layout in relation to the img and make them block display, so it’ll sit below your image on its own line).
- For cleaning up your code, I would just say that you should pull your inline styling out of your html files and put them all in your css file so they’re easier to keep track of
-Landing pages are always named index.html by convention, so I’d just updated that file from about_me.html to index.html

I’m not quite sure what you mean by being frustrated by how the images appear on the page — I’m guessing the resolution isn’t as high quality as you’d expect? If that’s the case, then that’s not you at all. Image quality isn’t something we can fix with basic css (there are whole image-serving platforms dedicated to it, so def not you). Good job putting those deliverables in a div to center them - creating wrapper divs is a common practice in CSS.

What kind of sizing specifically looks different to you from page to page? From dev tools the font size, etc looks identical from page to page.

This probably looks like a lot of feedback, but this is all minor stuff. Great job! :100:
