### ISSUE TITLE
Yanina Tsutieva-Class 4

### ISSUE THREAD

**Issue by yaninaTev** [Adamor/FEWD3.28#18]
Link to assignment: https://github.com/yanatev/FEWD328_Yanina
Comfort: 2
Completeness:2
Wins/Challenges: Becoming a little more comfortable with HTML/ still difficulty with CSS.

**Comment by heyyy-sebastian** [comment]
Hi Yanina -

This looks really good! You have a very solid start here -- there are only a few minor things to change with the file organization, and you should be all set. Even if this felt very difficult, this can be a very slow-going process in the beginning, so if you're ever feeling stuck, you can always send me a message on Slack or drop in during office hours.

- To get your css to apply to your html file, you can edit the link tag to be `<link rel="stylesheet" href="style.css">` This will make the styling appear if you open the file in your browser tab. You don't need to label it '/css' unless you have another folder named css where the style.css is going to be saved. Right now, all of the html & css files are saved in one folder together. 
- To split these html pages up into separate files, you can simply copy & paste your code for the "resume" page into another html file and label it "resume.html". It looks like you developed this in CodePen, which is a great place to practice styling things, but it's also important to save the files separately - right now it's all on one page.
- It looks like once you split up index.html and resume.html, the pages will link to each other because you set up the `<a>` tags correctly in your nav (I would wrap these anchor tags in an unordered list `<ul>` though, like we've discussed in class, because you're creating a list of links)

That should help with the set up, I just have a few other notes on your code:
- You don't want to use a `<nav>` more than once on a page. You can use a `<footer>` tag for links that are listed at the bottom
- For the About Me page, I would try floating your image to the right to see if you can get the text to flow around it
- If you wanted to match the paragraph font to the mock-up, I would use a serif font-family for the the p tags -- it looks like you tried to apply a specific font to those, but you're missing a closing quotation mark on line 59 of your css file

Otherwise your CSS is very clean and everything is succinct and well-organized. I would just work out the file structure and this is great! Good job :100:

**Comment by yaninaTev** [comment]
This was very insightful. Thank you!
