### ISSUE TITLE
home work

### ISSUE THREAD

**Issue by steven0633** [Adamor/FEWD3.28#19]
https://github.com/steven0633/FEWD328_STEVEN/commit/7f1c85e96a82ce51a6b5ac1dd30597e60862d8a6

steven acosta

**Comment by heyyy-sebastian** [comment]
Hi Steven -

This looks really good! I like your creativity with the photo haha

I have just a little bit of feedback on your styling:
- I would try to apply a different font to the headlines/paragraphs to more closely match the mock-up. You can use the font-family property in your css to update this
- Avoid styling your projects with both inline styling and css files -- putting all of your styling rules in one file is best because it's easier to keep track of your styling rules when they're all in one place, so you can pull your hr styles into the css file
- For naming conventions, the landing page of a website is almost always named index.html, so your about file can be updated to index.html
- the names of your classes are pretty good -- I can why you picked them, but I would make them a little bit more descriptive, even if you keep them short. Instead of "e" you could do "ed" because people generally recognize "ed" as an abbreviation for education
- I would try to update the color of your links, so they match the mock-up more closely
- Spacing in the form of padding/margins on the Resume page will make things look a little less crowded

Overall, this is very good! I can see you put some comments on your page of things you want to keep working on -- that's awesome, it's a good habit to keep track of what you've done and what you want to keep doing. Good job! :100:
