### ISSUE TITLE
Christine Fulcher - Homework Week 2 (Classes 3/4)

### ISSUE THREAD

**Issue by cfulcher87** [Adamor/FEWD3.28#20]
Title Section: Christine Fulcher - Classes 3/4 (Week 2)
Write Section:
Link to assignment: https://github.com/cfulcher87/FEWD328_CHRISTINE/commit/1ff295f0f54a369162d8227ffe281f82a474274f 

Comfort: 1-5 (5 being stellar, 1 being struggle bus):  4
Completeness: 1-5 (5 being complete, 1 being unattempted):  5
Wins/Challenges:  

Wins:  Flexbox success in the footer.  Also I once added 'clear' to something and it fixed EVERYTHING
Challenges:  Not easy - I probably over-complicated it and I it's not as clean as I would like.  At one point I threw something across the room.  Coding can be frustrating! 

Other comments:  Harder, but big success feelings.

**Comment by heyyy-sebastian** [comment]
Hi Christine - 

Coding can be very frustrating!!! Throwing things is okay, as long as it's not your laptop. Definitely take breaks if you feel like you're banging your head against the wall.

For all your frustration, this looks beautiful! Really nice job. Your html set-up looks great, just a few general notes:
- Overall the font could be a little bit bigger
- I would add more padding/margin on the sides of your text so there's more of a gutter and your eye is drawn to travel more down the center of the page
- When you add multiple classes to an html element, you don't need commas. `class="clear alignleft"` is best -- the compiler recognizes a space as the end of a class name for html when there are multiple classes on one item, you just need commas in your css file if you're styling one element AND another
- THANK YOU for commenting your css file. That's beautifully done, though you're right that there are a couple of places where you can refactor your code. I know we haven't talked about this a whole lot, but here are two main things I noticed:
1. you can refactor the properties themselves that you're declaring in your styles and
2. you can refactor how many times you declaring the same styling rule

For example, for number 1, you can shorten the padding rule on your benefits class on line 105. Shorthand for this property is `padding: [top] [right] [bottom] [left];` or even `padding: [top and bottom] [left and right];` so instead of `padding-top: 20px; padding-bottom: 20px;` you can change it to `padding: 20px 0;` so take another look at your styling sheet and see where you might apply this shorthand. More about other properties that can be written in shorthand here: https://developer.mozilla.org/en-US/docs/Web/CSS/Shorthand_properties

For number 2, if you find yourself writing something like `font-size: 20px;` more than once, chances are you can refactor this. You can apply styling to a specific element, then specify additional styling for multiple elements later on, and that first element will still retain the initial styles. That probably makes no sense to read, but here's what I mean: on lines 124-132 of your css file, you have `padding-bottom: 10px;` twice. This can be refactored as:

```
h3 {
    font-weight: 600;
    font-size: 20px;
}

p, h3 {
    padding-bottom: 10px;
}
```
So h3 has its own styles, then gets an additional style when it's declared in the group of elements, but still retains its font characteristics (which btw can also be refactored in shorthand), and that's one less line of code.

Excellent work! Great job seeing it through 👍
