### ISSUE TITLE
GABRIELLE ZANDI - Class 3/4 (Homework 2) - Section FEWD 3.28

### ISSUE THREAD

**Issue by gzandi** [Adamor/FEWD3.28#21]
**Assignment:** https://github.com/gzandi/FEWD328_GABI/commit/1c3568ca9388c948d7a7019813cf3b6f9c7ada40

**Comfort:** 4
**Completeness:** 5
**Wins:** 
-Overall continued comfort with HTML & CSS
**Challenges/Comments**
- Knowing when to use floats (or flexbox) and positioning 
- I tried to use floats for the buttons, but it didn't work, so centered with the text-align and padding. What should I have done? Should I have used flexbox? 
- My site wasn't responsive (specifically the bullets and the testimonial section). Was it supposed to be? If so, how should I have done this? Should I have used something other than pixels for the height (%) and the font size (ems)? 
- I had to make custom bullets to get the styling just right, how would you have done this? At first I set-up inline disks, but it left too much padding from the bullet to the text. 
- For some reason the italics didn't work for my google fonts (300i), I had to add additional italics. Can you see if there is something wrong with my code? It's odd since all of the other fonts worked correctly and when I put "300i" it still gave me the "light" (300) weight.

**Comment by heyyy-sebastian** [comment]
Hi Gabi -

This looks really good! 

To answer your questions:
- Floats vs flexbox is a contextual question because it sort of depends on the content of the website that's going to be scaling and which is easier to maintain as you scale it. Are you building it from the ground-up, or are you building on top of something that already relies heavily on one or the other? In my personal coding life, I've rarely used flexbox because that's not currently the industry standard, even though that's the direction in which things are moving (technology moves fast, giant websites get updated more slowly). I'm more comfortable with floats, so I use them more often, but I recognize that flexbox ultimately gives you more control over behavior. I would say get comfortable with both so you have the context of how flexbox evolved out of necessity from layouts/floats, and then pick the approach that best supports your content.
- For the buttons, I would try playing around with the styling rule `margin: 0 auto;` (you can adjust the 0 to different numbers/percentages as you wish); that's a lot of people's go-to for centering woes
- Responsive design relies on css media queries -- it's possible to have a website scale well, which yours does, but at a certain point you're going to need to write media queries to specify styling rules for smaller/larger screen sizes. We'll cover this in class, so don't be frustrated with the current display you have going -- it scales really well. Responsive websites are coded in pixels all the time, personally I like using ems, but pixels are definitely not the source of your layout breaking at smaller screen sizes. It's just a general limitation that css styling needs to be adjusted explicitly for certain screen sizes.
- I would try messing around with different properties for bullet formatting: https://css-tricks.com/almanac/properties/l/list-style/ inside/outside position might be what you're looking for, if not the text-indent can be set at a negative number to decrease space as well. 
- The font-weight property can only be declared as either an integer or bold/inherit/etc, so the css sheet doesn't know how to interpret '300i', only '300', you can declare font-style and font-weight in the same line of code, but there's more on writing in shorthand below

Other notes:
- I would try to be a little bit more descriptive with your class names. "container" is a good start, but "benefits-container" is more descriptive. You did a good job with this on your footer classes.
- Overall the font could be little bigger
- THANK YOU for commenting your css file so well, though you're right that there are a couple of places where you can refactor your code. I know we haven't talked about this a whole lot, but you can refactor a lot of these properties in shorthand.

For example, you can shorten the margin rule on your p element on line 174-175. Shorthand for this property is `margin: [top] [right] [bottom] [left];` or `margin: [top] [sides] [bottom]` or even `margin: [top and bottom] [left and right];` so instead of `margin-top: 10px; margin-bottom: 20px;` you can change it to `margin: 10px 0 20px;` so take another look at your styling sheet and see where you might apply this shorthand. More about other properties that can be written in shorthand here (fonts lend themselves well to this): https://developer.mozilla.org/en-US/docs/Web/CSS/Shorthand_properties

Excellent work! :tada:
