### ISSUE TITLE
Emily Panchame - Week 2, Day 4 

### ISSUE THREAD

**Issue by emilybpanch** [Adamor/FEWD3.28#26]
https://github.com/emilybpanch/FEWD328_EMILY/commit/2f0247929e12c3ac1f74cfc54b8922834af3bd24

Comfort: 3
Completeness: 4
Wins: I grew more comfortable with positioning in this assignment (hopefully I did it in a way that makes sense.)
Challenges: As a whole this assignment was pretty challenging and I did a lot of extra reading and research to help make things click. Biggest struggle was figuring out how to center-align those social icons. It was also a little challenging working in the CSS doc with a lot of markup already present (though I'm sure this is what you run into in the real world all the time!)

**Comment by heyyy-sebastian** [comment]
Hi Emily -

This is looking great! Getting used to positioning and layouts can be a long process before you get comfortable/work up the muscle memory for styling, so don't be discouraged. The process of troubleshooting and being able to research/google your way out of a problem is almost as important as getting your code up to spec, so I'm glad you were able to see it through. And yeah -- working off of pre-existing CSS happens all the time in the real world, and usually I deal with this by using Inspect Element to highlight different elements, so I can see some of the CSS rules that are there and then match them to the class/element styling in the CSS file itself. Your HTML & CSS is commented very well so I can understand how you organized things and your class/id names are semantic and descriptive.

w/r/t centering the social icons, there are a few different ways you can approach this. I think your initial idea to wrap them in a div is good, but it looks like you have an open `<li>` tag that could be causing some problems. There are lots of positioning rules applied to your social icons div, and sometimes less is more, so I would try applying those one at a time and seeing which one gets you closest to your desired alignment. Overall, center-aligning elements can be tricky -- I've found these posts helpful to review when I'm stuck: https://css-tricks.com/almanac/properties/b/background-position/ and https://css-tricks.com/centering-css-complete-guide/ I would also try playing around with the styling rule `margin: 0 auto;` (you can adjust the 0 to different numbers/percentages as you wish); that's a lot of people's go-to for centering woes.

Just a few other things to keep in mind:
- Overall the font could be little bigger
-  There are a couple of places where you can refactor your css rules. I know we haven't talked about this a whole lot, but you can refactor a lot of these properties in shorthand.

For example, you can shorten the padding rule on your .container-quote p element on line 166-173. Shorthand for this property is `padding: [top] [right] [bottom] [left];` or `padding: [top] [sides] [bottom]` or even `padding: [top and bottom] [left and right];` so instead of `padding-top: 10px; padding-bottom: 40px;` you can change it to `margin: 10px 0 40px;` so take another look at your styling sheet and see where you might apply this shorthand. More about other properties that can be written in shorthand here (fonts lend themselves well to this): https://developer.mozilla.org/en-US/docs/Web/CSS/Shorthand_properties

You can also combine elements to share styling rules, so on lines 208-220
```
.fb-logo {
  width: 10px;
  height: 20px;
  margin: 5px;
}

.tw-logo {
  width: 20px;
  height: 20px;
  margin: 5px;
}
```
can be rewritten as 

```
.fb-logo, .tw-logo {
  width: 10px;
  height: 20px;
  margin: 5px;
}
```

Overall this came together really well! Keep up the good work! :tada:
