### ISSUE TITLE
Stephanie Willhide - Class 4

### ISSUE THREAD

**Issue by stephaniewillhide** [Adamor/FEWD3.28#27]
https://github.com/stephaniewillhide/FEWD328_stephanie/commit/ac12a454e56bc69cebcd6b913db60eebbe370ae0

Comfort: 3
Completeness: 5

Wins: I got a better understanding of inheritance, and removing the default styling forced me to learn more about CSS in general.

Challenges: I found myself copying the selector for some elements and then styling that. It was useful for learning purposes, but I think my CSS file is really too sloppy and I could have organized my styles more efficiently. I'm not sure that adding tons of padding to everything was the right move, either. I added some comments, but it felt a bit awkward and I am not sure they are helpful. Next time, I hope to add them while writing the CSS rather than after, hoping that they will be more relevant.

**Comment by heyyy-sebastian** [comment]
Hey Stephanie -

You should absolutely pad the shit out of the things you build. That is more or less a direct quote from my instructor for the intensive course I took here at GA. Padding is great because it makes your page look spaced out nicely and not overcrowded as long as it's proportional to the elements around it. You could've even added some more padding to the testimonial quote OR (more common) added an explicit width (i.e. 40% or 200px or w/e) and centered it to make the text more of a focal point in the center of that div.

Copying the selector is a perfectly viable way to declare your styling rules. Sometimes you can shorten them, but not always, so just make sure you've tested them to see if you could say `ul > li` instead of `ul > li > selectors > and more selectors`. You don't always need the > symbol, sometimes you can just say `ul li`. That's not always the case, but you can check by doing cmd+f in the inspect elements window and copying the selector. If the selector is valid, it'll be highlighted in the html elements in the inspector (come find me and I'll show you if that doesn't make sense). Your css really isn't sloppy...like at all. It can be refactored in a few places, but it was easy to follow because it was like reading down the landing page. Your comments make sense, and it can be weird to comment things when it feels like you're stating the obvious, but it will help when I read it and when you come back to read it later.

Notes on refactoring: 
1. you can refactor the properties themselves that you're declaring in your styles and
2. you can refactor how many times you declaring the same styling rule

For example, for number 1, you can shorten the padding rule on your testimonial class on line 136. Shorthand for this property is `padding: [top] [right] [bottom] [left];` or `padding: [top] [sides] [bottom]` or even `padding: [top and bottom] [left and right];` so instead of `padding-top: 30px; padding-bottom: 30px; padding-right: 150px; padding-left: 150px;` you can change it to `padding: 30px 150px;` so take another look at your styling sheet and see where you might apply this shorthand. More about other properties that can be written in shorthand here: https://developer.mozilla.org/en-US/docs/Web/CSS/Shorthand_properties

For number 2, if you find yourself writing something like font-size: 20px; more than once, chances are you can refactor this. You can apply styling to a specific element, then specify additional styling for multiple elements later on, and that first element will still retain the initial styles. That probably makes no sense to read, but here's what I mean: on lines 205-212 of your css file, you have `padding: 20px;` twice. This can be refactored as:

```
footer > ul > li {
  display: inline;
}

footer > ul, footer > ul > li {
  padding: 20px;
}
```
So the li's in your footer have their own styles, then get an additional style when it's declared in the group of elements, but still retains its display characteristics, and that's one less line of code.

Other than that, I'd say just make the font in the benefits section a bit bigger and you're good to go.

Great job! :100:
