### ISSUE TITLE
n-Relaxr

### ISSUE THREAD

**Issue by yaninaTev** [Adamor/FEWD3.28#28]

**Comment by heyyy-sebastian** [comment]
Hi Yanina -

This is a good start, but you do need to upload your homework in a folder -- once you do that, I think you'll have an easier time linking your photos so they show up on your webpages. Here's an article about how these files are connected: http://learn.shayhowe.com/html-css/building-your-first-web-page/ It's long, but you already know most of it. You can save your html as a .html file in a folder if you're working on a project in a text editor, then open it in a browser by clicking "File > Open..." and selecting the .html file in the menu bar dropdown when you open your browser. Let me know if you want me to walk you through this during class one day or during office hours. Saving html and css files are the main way that we upload/share/display webpages, so it's important to get in the habit of saving your html & css files in an assignment folder.

Other than file structure, you have a really good start to this assignment. Your html elements are set up, though it's good to get in the habit of leaving a comment to note each of your sections so it's easy to read. You did a great job of positioning all your elements and spacing them out well, and your font is a nice size. 

Your CSS is excellent -- I don't actually have any feedback on that part because you've written the rules in shorthand. The only things that would be good to see here are comments to say where the styling rules are being applied, i.e. you can leave a comment above your footer styling rules that just says  `/*footer styling*/`. 

Let me know if you need help setting up/saving your files in a folder! 👍
