### ISSUE TITLE
Christine Purdy - Week 2

### ISSUE THREAD

**Issue by czpurdy** [Adamor/FEWD3.28#29]
https://github.com/czpurdy/FEWD328_CHRISTINE/commit/efa96c0990b50674c3208c65e1f5794ba4a299f6

Comfort: 3.5
Completeness: 5

Wins: I feel like I have a much better understanding of using HTML and CSS now. I found myself really taking the time to consider the several different ways I could accomplish a task and figure out which would be most effective. I was also able to clean up and organize my code more this time - yay!

Challenges: While I was able to troubleshoot which method would be most effective in each scenario, it required a LOT of trial-and-error. I know it will be very helpful long-term because it's teaching me to think more about the larger picture.

I did have a few smaller issues, most of which I addressed in comments. It was hard to perfectly match the deliverable (specifically certain colors or the sizing), but I think/hope it's due to the quality.

**Comment by heyyy-sebastian** [comment]
Hi Christine -

This looks awesome! Probably the most responsive layout I've seen yet (which wasn't a requirement, so extra kudos for being on top of things). Your thoughtfulness definitely shows in your html structure and your commenting is great, though I think you can use fewer classes overall. Your class names are excellent & descriptive, but you can also set a styling rule by declaring `div.benefits p` in stead of giving that paragraph an id (this way if you were building another page specifically about "benefits", you could generalize your p tag styling), or you could try `ul.benefits-content-list li` and adjusting the list formatting rather than applying a class in each line item. Here's some info on different properties for bullet formatting: https://css-tricks.com/almanac/properties/l/list-style/ I think those are the two that stand out to me, but other than that your naming conventions are good.

Re: your html & css comments:
- Try playing around with the margins on the elements and see how they move within their parent divs -- I think this is what you're getting at when you say spacing, so adjusting padding + margin is what you want here. If you mean spacing in terms of how much height each section takes up, I would just set a height explicitly, though I don't think that's what you mean because the proportions of your sections look good.  
- You can use line breaks in the footer just because it's usually not a content-heavy section and in this context it works, but could try using margins to space things out as well
- Don't worry too much about match the mock-up colors exactly, this mirrors the mock-up almost perfectly, and irl, you'll probably be given a color palette instead of being left to eyeball it
- This isn't formatting in terms of spacing, but I would make the benefits font a bit larger overall
- you can set both max-width and width for css if you use ems/percentages, so it will scale but not expand past a certain point once your screen size increases, this width is good because it covers pretty much all screensizes
- sry about the header img, weird stuff like that happens in design a lot and then it's like Uggghhh it wasn't even my problem
- using percentages is awesome and a good instinct for responsive design

Just one other thing about your code -- you refactor some of your css rules in shorthand. For example, you can shorten the padding rule on your header on lines 73-79. Shorthand for this property is `padding: [top] [right] [bottom] [left];` or `padding: [top] [sides] [bottom]` or even `padding: [top and bottom] [left and right];` so instead of `padding-right: 50px; padding-left: 50px; padding-top: 20px;` you can change it to `padding: 20px 50px 0;` so take another look at your styling sheet and see where you might apply this shorthand. More about other properties that can be written in shorthand here: https://developer.mozilla.org/en-US/docs/Web/CSS/Shorthand_properties

Really smooth Rick Roll in there.
Good job! :100:
