### ISSUE TITLE
Luke Degnan - Assignment 3

### ISSUE THREAD

**Issue by ldegnan** [Adamor/FEWD3.28#30]
https://github.com/ldegnan/FEWD328_LUKE/commit/fd03374704dbc6a9dc31ecf9d65d25ccb4145cc7

Comfort: 5
Completeness: 5

**Comment by heyyy-sebastian** [comment]
Hey Luke -

This looks awesome. I only have a couple of very minor notes about your css but your html structure/comments/naming conventions set-up are perfect.

For the appearance of the blog, I would just increase the left-hand margin on the left column sign it's aligned with the Relaxr title in the navbar, and maybe slightly increase the margin between the blog titles/images/Read More links.

For your css, there are a few places you can refactor your styling rules. For example, you can shorten the margin rule for your #rightcolumn on lines 195-202. Shorthand for this property is `margin: [top] [right] [bottom] [left];` or `margin: [top] [sides] [bottom]` or even `margin: [top and bottom] [left and right];` so instead of `margin-top: 40px; margin-right: 40px; margin-bottom: 10px; margin-left: 40px;` you can change it to `margin: 40px 40px 10px;` so take another look at your styling sheet and see where you might apply this shorthand. More about other properties that can be written in shorthand here: https://developer.mozilla.org/en-US/docs/Web/CSS/Shorthand_properties

Great work! 🎊
