### ISSUE TITLE
GABRIELLE ZANDI - Class 5/6 (Homework 3) - Section FEWD 3.28

### ISSUE THREAD

**Issue by gzandi** [Adamor/FEWD3.28#32]
Assignment:https://github.com/gzandi/FEWD328_GABI/commit/4c9a29fa4a85afc0dce334d0063605809e538007

Comfort: 5
Completeness: 5

Wins:
-Overall continued comfort with HTML & CSS
-Making a sitcky nav!

Challenges:
Overall it went pretty smoothly, the biggest challenge was formatting the navigation. For some reason, setting it to inline block and align right, didn't push the navigation all the way to the right, so I ended up using a float. Do you have any idea as to why this didn't work? 
Also I tried to make a pseduo selector for the nav at the end to make the last item (blog) grey to illustrate to the user that he/she was on the blog page, but it wasn't working so I left it out. I tried using both last-child and nth-child, with the ul, li and a elements but it didn't work :( 

Comments:
This was a nice way to wrap up the unit! I felt much more comfortable than I did in the past two homeworks.

**Comment by heyyy-sebastian** [comment]
Hey Gabi -

Really nice work! This looks good and your comments are detailed and informative. Thinking about it now, float is exactly what you need to use to get your elements to the right in the nav bar because text-align right will push each element to the right within the list item blocks, but floating the ul to the right pushes it to the right within the navbar parent div. Since the list items are nested within the ul which is nested within the navbar, you need to target the highest parent div. Text-align will move things to the right, but only within the specific divs where there's text and only within that element.

For the pseudo selectors, this is tricky because you're troubleshooting something that's not a live webpage, so the browser needs more specificity in the href link to know that the page it's on is the active page. When I open this on my computer, the file path is `file:///Users/hmiller/Downloads/FEWD328_GABI-master/homework3/index.html` so if I inspect element and copy that into the href url and select the `<a>` in the elements and then at the top under the styles tab, where there's the greyed out `element.style{}` block, you can click the :hov filter, click active and add `color: white;` into the `element.style{}` block and the blog color will highlight white. These are just steps for testing to show you that the active pseudo element can work - in this case, it's just the specificity url that the browser needs to render that styling. Watch here: http://recordit.co/Wnu7YaVWyz.gif (it gets cut off a bit at the end, but you can probably test using this as reference)

The only other feedback I have is that you can still refactor some of your styling rules in shorthand (.i.e. your padding rule on line 171-172 can be rewritten as `padding: 2% 10% 0 0;`) and add a bit of a larger margin between the right rail and the main content.

Nice work with the hover states and sticky nav! :100:
