### ISSUE TITLE
Christine Fulcher - Week 3 Homework

### ISSUE THREAD

**Issue by cfulcher87** [Adamor/FEWD3.28#34]
Title Section: Christine Fulcher - Class 5/6 
Write Section:
Link to assignment: https://github.com/cfulcher87/FEWD328_CHRISTINE/commit/a5a42b0a3c427aa9294aa468f7d22ee00dabcdfa

Comfort: 1-5 (5 being stellar, 1 being struggle bus):  4.5
Completeness: 1-5 (5 being complete, 1 being unattempted):  5
Wins/Challenges:  Getting much, much, much faster

Other comments:  I like labs in class :)

**Comment by heyyy-sebastian** [comment]
Hey Christine - 

This looks really good! It matches the mockup very closely. 

Minor notes:
- Your html looks good, I would just throw in a few comments to mark out the different page sections 
- When you apply multiple classes to an html element, you don't need to separate them with commas in the html doc. You can just write `<div class="flex-item Yellow">Relaxr</div>` and the browser will know that it should get styling from both the .flex-item AND the .Yellow classes that are in your css file
- To more closely match the mockup, I would try to have the nav and the footer take up 100% of the width of the browser window, and then put the blog content/aside in a container so it'll retain the gutters on either side like in the mockup
- There are a few places you can use shorthand for writing your padding rules (mostly just for your drop case lettering) in your css file
- I'd enlarge the Sign Up Now and Read More buttons, just because those are things you want to pop out of the page for user engagement

w/r/t the padding halp: your selector is a little bit off in your css file. If your selector is `h4 ul:last-child` you're saying that your elements are nested like this:
```
<h4> hello this is an h4 element
<ul>
<li>with a ul nested inside of it</li>
<li>and this is the last child </li>
</ul>
</h4>
```

But! that not how your page is structured. Your h4 element's SIBLING is the ul, not its child. Siblings are next to each other, children/parent elements are nested within each other. Honestly idk a use case for embedding a list in an h4 tag because if you wanted larger text, you'd just set the font size to be bigger rather than relying on the default font-size of the h4 tag.

Anyway, your ul doesn't have any margin around it, so if you applied a margin to the bottom of it, it should space things out. Same with the space between your main content and your aside: you could add a bit more space between the two column by adding margin-right to the main content.

Great work! This one was easy and clean to read. 👍
