### ISSUE TITLE
Emily Panchame - Week 3 Homework

### ISSUE THREAD

**Issue by emilybpanch** [Adamor/FEWD3.28#35]
https://github.com/emilybpanch/FEWD328_EMILY/commit/33eab435de291bcad42338e5b761a3158603a643

Comfort: 4
Completeness: 4
Wins/Challenges: I grew a little more comfortable with layouts and using floats and clear-fix in this exercise, as well as using pseudo elements for the drop cap and button/link hover effect. Sometimes I'm still unsure of how to position an element -- like indenting the nav items for instance. I included a lot of left padding, but something tells me there's a better way to do it. Figuring out how to align the "read mores" was a little tricky. Something is off with the links in the top nav...they're there but don't seem to be aligned with the text, and the hover effect wasn't working. I also couldn't figure out how to reduce the space between the articles (floated left) and the sidebar (floated right). And finally, it seems straightforward when I read about it, but sometimes I'm still not sure whether to use margin or padding. I usually end up trying both and going with the one that looks right. I'm wondering why there's extra space to the right of my footer and aside. 

Other comments:
Sorry for being so late with this one. I was traveling Thursday night through Monday night so I wish I had a little more time to sit with this/research my questions.

**Comment by heyyy-sebastian** [comment]
Hi Emily - 

This looks great! The sizing/spacing of all your text/photos/buttons looks really nice here. Floating the Read More is a perfectly viable way to do it & I would've done the same; the element that you choose to wrap it in subjective because div/span/p tags are all options that can be floated the same way. Padding is also a good way to space out list items; the choice between padding or margins depends on a) how big you want your elements to be (padding) and b) how far apart you want your elements to be from each other (margins). So the approach will depend on your content and how you want your layout to scale (not essential right now, but just for future consideration if you're working on a mobile website or something, padding/margins play a role in responsive design).

I think your nav text is aligned with the Relaxr title, so that's possibly an optical illusion from text color differences?

The hover state for your Learn More needs to be wrapped in an anchor tag separately from the div. It looks like you started to put an anchor tag in there, and then had a typo. So `<div a href="#" class="more">Read more ></a></div>` needs to be `<div><a href="#" class="more">Read more</a></div>` Same with the list items in the nav bar, `<a></a>` tags are their own html elements, not an attribute that goes inside an element. Once you have those in there, the selector needs to walk down the whole tree of your elements to find the anchor tag, so if you write `ul a` in your css, your styling won't get applied because the computer doesn't see any direct children that are an "a" under the ul. The "a" tag here is more like a grand-child because it's under the li under the ul, so the selector needs to point to the ul, then the li, then the a tag, because it needs to step from one element to the next when they're nested inside each other. Try `ul li a:hover` and see what happens.

So when you float an element, it will go aaaallllll the way to the side that it's floated to, so your columns are hugging the right & left side, respectively, and don't care about whether or not there's a space between them. So to adjust the space on floats, you need to add a margin on the right for float: right and margin on the left for the float: left to push them more towards the middle.

Other than that, it looks like all your css is written in shorthand and the appearance is great. This isn't late at all! This is solid regardless of how much you've been traveling. 🎊
