### ISSUE TITLE
William Wilcox - Assignment Week 3

### ISSUE THREAD

**Issue by wilcoxwc** [Adamor/FEWD3.28#36]
Write Section: CSS and floats (aka - fun time)
Link to assignment: https://github.com/wilcoxwc/FEWD328_WilliamWilcox/commit/3244cebacd292dca3d621f42a20413209aa17ee8

Comfort: 4 
Completeness: 4

Wins: I am really starting to understand how to understand classes and inheritance of rules within CSS. It was easy for me to fix problems that were hard in the past.

Challenges: For some reason I couldn't get the code to change with different browsers. I believe I implemented the correct CSS, but still no go. Also, I am slowly understanding how to match the design needs of a client, but that sense is coming a little slower than just understanding the code. I have a feeling that is going to lock in once I get the method down

**Comment by heyyy-sebastian** [comment]
Hi Will -

This is a solid start! The set-up of your html file is great, I just have a few notes on your layout/css:
- To more closely match the mockup, I would try to have the nav and the footer take up 100% of the width of the browser window, and then put the blog content/aside in a container so it'll retain the gutters on either side like in the mockup. Generally speaking, yes, matching design needs gets easier the more you practice and develop the muscle memory for coding this type of stuff
- your html is indented well so I can tell how things are nested, but I'd throw in a few comments to denote different sections
- Add a bit more of a margin between the two content columns/between the read more and the footers to space things out a bit
- For drop case letters, this is a good place to start: https://css-tricks.com/snippets/css/drop-caps/
- I think you have an extra `</div>` closing div tag before your img tags in your footer (probably an autocomplete thing)
- For shaping the Sign up buttons, play around with the border-radius property in your css
- If you find yourself using the same class on elements that are nested within a parent element (like your list items for example), you can you `ul.nav-style li` or `ul.nav-style li a` to target the lower elements, rather than crowding your html with class names
- you've styled your `footer > h1` element twice in your css

I'm not quite sure what you mean by having the code change in different browsers? Generally consistency is what we aim for across browsers (chrome/firefox/safari etc), so you've linked to the reset.css correctly.

Do you mean linking pages to one another? Like being able to click back and forth between About pg/Blog pg? That's a little bit tricky when you're just opening the files from your computer, because you have to explicitly set the href to the file path on your computer (i.e. href="file:///Users/hmiller/Downloads/Class_lab_and_Assignment_3/index.html#"), rather than just the html file that your browser gets from the live server (href="/index.html").

Good job! 👍
