### ISSUE TITLE
Michelle Hsuw week 3 hw

### ISSUE THREAD

**Issue by michellehsu** [Adamor/FEWD3.28#41]
Link to assignment: https://github.com/michellehsu/FEWD0328_michelle/commit/53658e355f6bce1bdd1b18813f430d2e8a7d85d0

Comfort: 1-5 : 5
Completeness: 5
Wins/Challenges:

Other comments:

**Comment by heyyy-sebastian** [comment]
Hey Michelle -

This looks great! The comments in your html are perfect and the you've chosen the right elements for the different kinds of content. The layout looks good, I would just add some padding/margin between the two columns in the main content well.

One thing I noticed in your css is that you sometimes declare a styling attribute twice in the same styling block. For example, one lines 74-80, you have `margin: 0 auto;` and `margin-top: 50px;`. When you do this, your css ends up ignoring the first rule. The computer compiles the styles in a cascade (hence the name cascading style sheets), so the second rule overwrites the first rule that you've set. If you inspect your #sidebar in DevTools and uncheck `margin: 0 auto` nothing happens because that styling rule isn't being applied. You can combine these rules in shorthand as `margin: 50px auto 0;` because it can be written as `margin: [top] [left and right] [bottom];` 

You've used the shorthand for this elsewhere in your css, so I'd just glance back through and see where else you can apply that pattern. 

To style the "Learn More" button, I think the selector you're looking for is `#learnmore a` because the anchor tag contains the tag that actually ends up containing the text, so you need to walk down all the way to the `<a>` tag to get the color onto it.

Otherwise this is great! Good work. 👍
