### ISSUE TITLE
Gabrielle Zandi - Week 5 Homework

### ISSUE THREAD

**Issue by gzandi** [Adamor/FEWD3.28#44]
https://github.com/gzandi/FEWD328_GABI/commit/41a6f3cd9fa18f90c24f857472f727cda9fb665b

**Comfort:** 5
**Completeness:** 5

**Wins:** Thought the assignment was relatively easy, but since it didn't test most of what we learned in class, I'm sure there is a lot that I still need to practice! 

**Challenges:** More questions rather than challenges: 

1. How can I consolidate code better? For example, 

$("#show-this-on-click").show(); 
 $(".readless").show();

Can I consolidate this into the same line? I tried $("#show-this-on-click .readless").show(); but it didn't work. Does this have anything to do with combining IDs and classes? 

2. How can you maintain scroll position? Everytime I clicked a button, it would scroll back to the top of the page. I went into Stackoverflow, but it seemed that there are a lot of ways to do this, but they all seemed pretty complicated. Any suggestions here?

**Comment by heyyy-sebastian** [comment]
Hey Gabi -

This looks good! You've got a handle on jQuery.

To answer your questions:
1. When you try $("#show-this-on-click .readless") you're telling jQuery to look for the element that has both this class & ID, so it's looking for the selector `#show-this-on-click.readless` but this particular selector doesn't exist in your html. Much like css, you can try separating these selectors with a comma rather than chaining them together, so `$("#show-this-on-click, .readless")` will probably do the trick.

2. To _prevent_ this _default_ behavior of jumping back to the top of the page, I would implement a method you've already used once in your js file in your click functions...

Good work! :100:

**Comment by heyyy-sebastian** [comment]
Oh! also, rather than `$(".hide").hide();` on load, you can set these elements as `display: none;` in your css, and calling the `.show();` method will change the display rule.
