### ISSUE TITLE
Emily Panchame - Homework 4, Week 5

### ISSUE THREAD

**Issue by emilybpanch** [Adamor/FEWD3.28#46]
Comfort: 4
Completeness: 5
Link: https://github.com/emilybpanch/FEWD328_EMILY/commit/9eeb6e4e3febf0009b86c2237015ab6456a3d277

**Wins:** I was pleasantly surprised with this assignment because I thought it was going to take me a lot longer to wrap my head around this, but it wasn't too bad (partially because the homework instructions told us what functions to use vs. just saying "prevent the default action from happening.") In general I knew which CSS selectors to use and how to set up the functions. Curious to see what the feedback is since there may be better or more succinct ways of doing what I did.

**Challenges:** I added a "Learn Less" link in the aside and, for whatever reason, it took me awhile to figure out how to use $.slidedown and $.show that link along with the "learn more" text (and also have it not affect the other hidden elements on the page). I think because it was a link within a span within a paragraph it was a bit trickier than the "read more/read less" example.

**Comment by heyyy-sebastian** [comment]
Hi Emily -

This is great! You have all the functionality working, but there are a few ways you can consolidate your code to make it shorter.
One thing you can do is to move all the methods you want to run into the same .click() function.
So if you want multiple elements to be animated when ".readmore" is clicked, for example, you can take this code:

```
/when 'read more' is clicked, slide down/

	$(".readmore").click(function(){
		$("p").slideDown();
	});
	
	/when 'read more' is clicked, reveal 2nd paragraph/

	$(".readmore").click(function(){
		$("p").show();
	});
```

And write it as:

```
$(".readmore").click(function(){
               $("p").slideDown()
		$("p").show();
	});
```
So it runs the same as your code now, it's just easier to read because you can see EVERYTHING that's going to be animated when ".readmore" is clicked in one space.

Another way to shorten this is to "chain" methods to each other when you're targeting the same element. So instead of writing:
```
$(".readmore").click(function(){
               $("p").slideDown()
		$("p").show();
	});
```

You can move everything to one line as:

```
$(".readmore").click(function(){
		$("p").slideDown().show();
	});
```

The only other feedback I have is that you could use preventDefault again in your `.click()` functions so the page doesn't jump back up to the top.

Good job! Having the paragraphs be animated independently of one another has definitely been a sticking point for a lot of students for this assignment, so I'm glad you figured that out. Your comments in your js file are great. :100:
