### ISSUE TITLE
michelle hsu: week 5 hw

### ISSUE THREAD

**Issue by michellehsu** [Adamor/FEWD3.28#50]
Link to the assignment: https://github.com/michellehsu/FEWD0328_michelle/tree/master/week5/homework/starter_code
Comfort: 3
Completeness: 4

Challenges: i think i understand the most part how jquery works while doing exercise in class.  However when I started to do on my own from scratch, it took me a while to link js file and set up js structure (ie, $(document).ready, etc) to actually make it work. I did a few more tutorial on dash and codeacademy to figure it all out.

**Comment by heyyy-sebastian** [comment]
Hey Michelle -

This looks great! It's clean and succinct and works well. It's normal to feel comfortable doing exercises in class and then hit some road bumps when you try to set everything up on your own. Doing stuff in class is always easier because you can reverse-engineering your understanding if you get stuck, but can get the answers for reference, so doing things on your own is always tougher. I hope the dash/codeacademy tutorials helped -- it looks like they did because everything is working & honestly learning how to effectively research a problem while debugging is a large chunk of the programming process 👍 but also feel free to slack me if you have extra questions. Even if I'm not online/if it's not technically office hours I can get back to you if you haven't been able to google your way out of a problem.

Great work! :100:
