### ISSUE TITLE
Christine Purdy Homework (Week 5)

### ISSUE THREAD

**Issue by czpurdy** [Adamor/FEWD3.28#52]
https://github.com/czpurdy/FEWD328_CHRISTINE/commit/4ed040c5d2a76d9e4cf2e0c6ce7cce6f84c6c3b5

Comfort: 4ish
Completeness: 5

Wins: I have a greater understanding of jQuery and am getting a hang of learning to write code out without copying and pasting (although there's a lot of troubleshooting!). I was also able to spend more time considering how I wanted things to look and spent more time trying out which ways were best.

Challenges: LOTS of trial and error. Lots of googling/research. (BUT lots of learning as well!).

**Comment by heyyy-sebastian** [comment]
Hello!

This is great! I know you were feeling like JS is generally a lot and kind of overwhelming, but you're definitely getting it. The *~user experience~* of your slideUp/Down animations is pleasing/smooth, and I don't see anywhere where you could refactor this. 

When you're first starting out everything takes a lot of googling/troubleshooting, but once you're more familiar with jQuery you'll be able to spot your errors more quickly. Computers are generally stupid in the sense that they take everything literally, so that leaves a lot of room for error on our part when we're not specific/explicit enough in our instructions, because at the end of the day the computer just wants a simple yes/no direction (yes, remove that; no, don't show that, etc). There have been plenty of times when the answer ends up being a lot simpler than I initially thought 😬 

Good work! 🎊
