### ISSUE TITLE
Week 6 Homework

### ISSUE THREAD

**Issue by wilcoxwc** [Adamor/FEWD3.28#53]
https://github.com/wilcoxwc/FEWD328_WilliamWilcox/blob/master/homework.zip

Comfort: 4
Completeness: 4

Wins: I was able to get the two blog entries to expand and contract. I still need to work on the structure of the page though.

Challenges: I used the same method on the sidebar as the blog entries. It still is not behaving as I expect and still can't figure it out. My biggest challenge still seems to be more the structure and ensuring the page renders correctly.

**Comment by heyyy-sebastian** [comment]
Hey Will -

This is looking good! 

Just a few notes:
- You can wrap all of your js code in the document ready function. This is typically the wrapper function for all the jQuery code you write. When you put all your code inside this function, it helps prevent load errors, is cleaner, etc. So it will look something like this: 

```
$(document).ready(function(){
//ALL your code goes here

});
```
- To prevent the page from jumping back up to the top on click, I would look at how to apply the `.preventDefault()` method to the animations you have in your on click functions (this will fix your sidebar reveal problem)
- Rather than $("selectors").hide(); on load, you can set these elements as display: none; in your css, and calling the .show(); method will change the display rule, so you ultimately end up writing less code
- Using IDs as a target for animating elements is fine in the context of this assignment, but IDs have such an intense specificity that they ultimately won't scale well (i.e. if you had a blogroll of 50 articles on a page, it would be annoying to write the same show more/less for 50 individual articles). I would try looking at this article and see if you could apply the `.next()` method to a button class to get the paragraphs to animate individually with less code: http://stackoverflow.com/questions/6713059/expand-p-when-h1-is-clicked

Good work! 👍
