### ISSUE TITLE
Week 5 Homework - Christine Fulcher

### ISSUE THREAD

**Issue by cfulcher87** [Adamor/FEWD3.28#56]
https://github.com/cfulcher87/FEWD328_CHRISTINE/commit/4cef2bb71eaad45726938e141740f2a734204b9f

Sorry it's late :( 

Completeness:  4.5
Understanding:  5.0 (once I got Javascript actually working!)

**Comment by heyyy-sebastian** [comment]
Hi Christine -

This is excellent! I only have one piece of feedback about your javascript, which is that instead of wrapping all your code in an anonymous (unnamed) function, just wrap it in the document ready function. This is typically the wrapper function for all the jQuery code you write. When you put all your code inside this function, it helps prevent load errors, is cleaner, etc. So it will look something like this:
```
$(document).ready(function(){
//ALL your code goes here

});
```
Great work! :100:
