### ISSUE TITLE
week 6 homework - luke degnan

### ISSUE THREAD

**Issue by ldegnan** [Adamor/FEWD3.28#57]
https://github.com/ldegnan/FEWD328_LUKE/commit/71bb9a60eca3b908b2c1f38e7361ee336a63b876

Comfort: 3 
Completeness: 4 
Challenges: I just can't get the text to wrap on the main page. I'm not sure what I'm doing wrong. Honestly, I didn't have as much time to put in to this as usual so I'm thinking that had something to do with it.

**Comment by heyyy-sebastian** [comment]
Hey Luke -

This is looking good! To get your text to wrap on the main page, you'll need to reset the `#benefits p` width that you have set at 600px and the width of your `blockquote` element; additionally, word-wrap is a good property to consider, as is `overflow-x:hidden;`. You don't need to specify 0px as the min-width, because that's assumed, so just writing `@media all and (max-width: 400px) {/*css goes here*/}` is sufficient. Other that that, this looks great! Good job making it through the mobile bullshit 👍
