### ISSUE TITLE
Week 6 Homework - Christine Fulcher

### ISSUE THREAD

**Issue by cfulcher87** [Adamor/FEWD3.28#60]
https://github.com/cfulcher87/FEWD328_CHRISTINE/commit/1255b9b23e88084c96486c5b7ce9f6ff38c4624f

Completeness:  5
Mastery:  4.5

Commentary:  I just knocked this out, definitely needs refactoring and I could have added the hamburger I created in Lab.  But I'm just trying to roll through homework so I can get to Final Project!  Forgive me.

**Comment by heyyy-sebastian** [comment]
Hi Christine,

Understandable that you're trying to focus on the final project -- that's ok! You understand how media queries work and how to set them up/where to include them in your css file, so that's what's important. There are a few places where you could use css short-hand, but you'll probably be able to spot those if you look at this again.

One thing to keep in mind is that if multiple pages share the same classes, the styles you set in a media query will be applied across pages. For example: you container class looks good on the homepage, but on your blog page it's throwing off your two-column layout.

Good job! 🎉
