### ISSUE TITLE
Homework 5, Week 6

### ISSUE THREAD

**Issue by emilybpanch** [Adamor/FEWD3.28#61]
Comfort: 3
Completeness: 4
Link: https://github.com/emilybpanch/FEWD328_EMILY/commit/69c7f7206eea8b7b8b493bb5505020cc9c0ca04e

**Note:** For some reason the blog.html file, images, and reset.css files weren't showing up in my github folder to merge, even though they were in the folder on my computer. So you'll just see the style.css and index.html docs here -- but the css encompasses the blog.html as well. If you need me to recommit let me know, but I couldn't figure out where I went wrong.

**Wins:** Once I figured out the media query display properties for mobile it was fairly easy to repurpose them for the tablet size. I found that closely mirroring the css already in place was a good way to readjust elements for mobile/tablet (seems obvious but wasn't to me at first).

**Challenges:** This homework was fairly difficult for me because we didn't cover responsive design in depth in class, although the responsive lab in our last class definitely helped. I tried adding a hamburger menu for mobile (by adding the icon in the html, adding "display-none" in the main css and specific display properties in the media queries, and using a simple show on click jquery function), but I was having issues so eventually just went with a shortened nav menu 
on mobile which I think is still workable, but not ideal. I have a feeling my css could be a little tighter. I was a little unsure of the best way to size and align elements for mobile and tablet -- I tried to keep some uniform rules but a lot of times I was just seeing how the pages rendered in the DOM and adjusting from there.

**Comment by heyyy-sebastian** [comment]
Hi Emily -

This is good! I'm sorry the repo didn't sync correctly - I can still open this and test it but I'm sorry GitHub was being a pain.

Anyway, this is looking good. I would add little bit more padding to the nav bar on the mobile-iPad range, but this display could also be the result of the css resets missing. It scales well and your approach for re-tooling the existing css rules is on point. I usually look at how my elements are showing up on the page, and then adjust from there, so I don't think there's anything wrong with styling things based on what you see in the DOM, as long as you don't repeat styling rules. I find it easiest to start with my biggest elements/sections and work my way down. Usually adjusting the larger elements means that you don't always have to mess with some of the nested items because they inherit some of the display rules from their responsive parent elements.  

For sizing on mobile and tablet, the basic rule is that your content should still be legible without being too big or too small. That probably sounds vague, but if your website has content for someone else to consume, it holds up that tiny text/pictures are illegible and larger text/pictures are a pain to scroll through. Basically you're trying to create the optimal number of words per line for reading comprehension. It probably varies from language to language, but there's some interesting science behind it: http://webstyleguide.com/wsg3/7-page-design/6-page-width-line-length.html The more the user can comprehend, the longer they stay engaged, and the longer they keep using your site/product.

There are a few places where you can refactor your css rules in short-hand, but you'll probably be able to spot those if you look at this again.

Here's a short/basic hamburger menu on codepen that might help you get unstuck in your click-reveal for the mobile menu: https://codepen.io/g13nn/pen/eHGEF 
 Don't forget to `.preventDefault();` on click events.

Good job! 👍
