### ISSUE TITLE
Week 5 Homework

### ISSUE THREAD

**Issue by wilcoxwc** [Adamor/FEWD3.28#62]
Comfort: 3
Completeness: 3
Link: https://github.com/wilcoxwc/FEWD328_WilliamWilcox/blob/master/homework.zip

Note: I had a great beat on the CSS and mobile rendering and then something broke. I spent most of the time trying to debug but even in the DOM I think I mixed up classes. 

Wins: I now understand how to properly order my CSS, in the opposite way of course. One of the challenges I had was finding the mobile version of a certain class. I'll be grouping the different media classes together as opposed to each version of each class together.

Challenges: Sidebar and the footer gave me the most trouble. I couldn't figure out how properly get them to render in the mobile view.

**Comment by heyyy-sebastian** [comment]
Hey Will -

This is a good start, but I think part of your debugging grief is coming from how many media queries you have in your css file. I'm not sure if this is what you were getting at in your wins comment, but a media query should go at the end of your css file and can be structured like this: 

```
@media (max-width: 768px) {
// ALL your styles for iPad screen size go here
// every single one
// all of them
  }
```
I like to think of it as a style-sheet within your style sheet. This way, you won't have classes overriding each other in media queries that you write later in your style sheet. It's hard to get to the root of your styling issue when it could be coming from multiple media queries. 

Another useful thing to do when debugging is to hover over the elements one by one in the devtools Elements tab. It will highlight the margin/padding, so you can see how much space things are secretly taking up. For example, your "container" width is still set to 960px in your hero section on the landing page. Once you get a handle on the widths of the elements inside different sections, you'll probably have an easier time getting things to render how you want them to because you'll know where to reset the styling.

Good work! 👍
