### ISSUE TITLE
FEWD3.28-Gabrielle Zandi-Week 7-Homework

### ISSUE THREAD

**Issue by gzandi** [Adamor/FEWD3.28#64]
https://github.com/gzandi/FEWD328_GABI/commit/ac24991e8e9c24a9788ab6f6f643644097a53f8e

**Comfort**: 2
**Completeness**: 5

**Wins**: mmm... I came, I struggled hard... and eventually conquered with the help of Halie (thanks again).

**Challenges**: I found this to be the most difficult assignment thus far. I think I need more practice in general with javascript and jquery and wasn't ready to add forms and apis on top of it all. I'm glad I learned this, but felt that since this was so over my head, I was throwing spaghetti at a wall to see what stuck instead of critically looking at the problem and solving it.

**Comment by heyyy-sebastian** [comment]
So obviously we worked through this together, so I know you're getting this, but overall I think there were a couple things that threw you off, which then made you feel like you needed to throw things. I'd say general checks that are good include: check your document-ready wrapper function, include prevent default, use `console.log("hello")` as various points in your functions to see if the function is being hit at every stage (like if there's a for loop inside a click function).

You got it once we got through some of the set-up issues, but I would give yourself some credit because you made it through an assignment without actually being in class when we covered it. The main take away here is that ajax is a method that we use to ask APIs for information.

The last thing I would say is that you can append the information you printed in the console to your DOM, so the user can see the weather feedback on the page instead of just in the console. 

So when you get that object back, after you console.log the data, you can parse through the object (like when we talked about accessing car info using car.model, car.year) to get info that we can add to the DOM. e.g. inside your success function you could write something like:

```
town = json.city.name;
temp = json.list[0].main.temp;
$(document).append("In " + town + "it is " + temp + " degrees F.")
```

and that should add the info to your page, though I would maybe specify a tag that you want to ad that to.
