### ISSUE TITLE
Christine Fulcher - Week 7 Homework

### ISSUE THREAD

**Issue by cfulcher87** [Adamor/FEWD3.28#65]
Link:  https://github.com/cfulcher87/FEWD328_CHRISTINE/commit/5629ca98afb63d1843e16595a9fadc4331b4a7c9 

Completeness:  4
Understanding:  4

Comments:  Couldn't connect from City Name to City ID for the url but think it might be structured OK?

**Comment by heyyy-sebastian** [comment]
Hi Christine -

This great! You're very close. Just a minor house keeping thing - the script tag on your index page has two src="" attributes, so delete the one that doesn't point to you main.js file, and you're missing the closing }) on your document ready wrapper function.

For your city variable, you're actually grabbing the right input for the city, but you've assigned it to the variable input on line 17, so when you try to console.log(city) city is undefined because there isn't a variable named city that's been declared, there's only `var input`. If you console.log(input) you'll see the zip code printed out in the console. You can then put this variable name (you can keep input or name it city, either will work) in the url line, and this will be mostly good to go.

The last thing (which is hard to catch) is that your appid has the parameter 'us' in front of the appid number. So that parameter will tell the API that the zip code is in the US, but when you structure a URL request, the first parameter follows a '?' in the URL, and the rest of them are separated by '&' symbols. So if your were searching for books, the url might look like `/books?author=authorName&title&yearPublished` So as it is right now, the appid will cause an error because it either needs to be '&us' or you can remove it (because this API defaults to the US) and just have "&appid=....." If you do that, you're good to go!

Awesome job! 🎊
