### ISSUE TITLE
FEWD3.28-William Wilcox 7-Homework 

### ISSUE THREAD

**Issue by wilcoxwc** [Adamor/FEWD3.28#66]
Link: https://github.com/wilcoxwc/FEWD328_WilliamWilcox/blob/master/weatherapp.zip

Completeness: 4
Understanding: 4

Comments: Outside of cleaning up the HTML I was able to really understand JS and how to pull data from both an object and an array into my web page.

Challenges: I still need to get my CSS and design skills down. That will be the main challenge for my final project. I understand data very well.

**Comment by heyyy-sebastian** [comment]
Hey Will -

This looks really good! Normally convention is to use a `<form></form>` tag to take in the input to get the API data, but what you have here is the same output, so that works. 

My only feedback is that the "Upcoming" weather data comes back as undefined for me, so maybe they've changed their object structure since you submitted this, but you definitely get APIs & parsing data.

Great job! 🎉
