### ISSUE TITLE
Homework 6, Week 7

### ISSUE THREAD

**Issue by emilybpanch** [Adamor/FEWD3.28#67]
**Link:** https://github.com/emilybpanch/FEWD328_EMILY/commit/298a6cf4ea2781c2f2b85cd733b5800e4d6b64d9
**Choice 2**
**Completeness:** 4
**Wins:** Building and styling the form wasn't too bad. I chose this homework because we use a lot of forms on the websites I work on at work.
**Challenges:** I couldn't figure out how to override the default styling for the drop-down menu (I was able to change some elements, but not the border-radius).  I also couldn't figure out how to trigger an alert when the form submitted. I looked up a few different resources and it seemed like there were different ways of doing it, so I tried a few different things, but in the end I couldn't get it to work. I should spend more time on this (and do the extra credit) but I wanted to work on my final project.

**Comment by heyyy-sebastian** [comment]
Hey Emily -

This looks really good!

I wouldn't worry too much on overriding the default styling on the drop-down menu because it's practically impossible on any browser. Chances are if you see a drop-down that's beautifully styled, they've probably built a form that has a bunch of customized divs set to act like options, which is risky, or they've used JS to style, which isn't best practice either. More on what you can/can't style here: https://css-tricks.com/dropdown-default-styling/ 

For triggering the form on submission, it looks like you have a couple of syntax issues in your JS file. Specifically I would look at the closing brackets on the click function and think about using preventDefault.

Great job! 🎉
