### ISSUE TITLE
Christine Fulcher - Week 1 (Classes 1/2)

### ISSUE THREAD

**Issue by cfulcher87** [Adamor/FEWD3.28#7]
Link to assignment: https://github.com/cfulcher87/FEWD328_CHRISTINE/commit/8ce1797b040d9840322a0e2f9bb9c4996863c445 

Comfort: 1-5 (5 being stellar, 1 being struggle bus)  4
Completeness: 1-5 (5 being complete, 1 being unattempted) 5
Wins/Challenges:  It drove me crazy but I couldn't figure out how to ensure my image didn't cover up my horizontal line on the "About Me" section.   Couldn't quite get it, everything else felt comfortable... eventually. 

Other comments:  I got insanely more efficient as I built out the second tab, kept going back to the first to clean up my first try.  Really looking forward to seeing the most efficient way to code this.

**Comment by heyyy-sebastian** [comment]
Hey Christine -

This looks excellent! You have a solid grasp on what we've covered so far. Things will definitely pick up as you internalize styling and HTML, so being efficient is ultimately muscle memory that comes from practice.

w/r/t your pictures: image positioning is tough, it's still a constant source of frustration for me, so don't panic about not getting it right away. The issue here might come from where your image element is on the page. I would try moving it down into div.main and see if you can get the text to flow around the image, since it looks like all those elements belong in the same div from the mock-up. More about floats here: https://css-tricks.com/all-about-floats/

A few other things:
- Naming convention for files are usually that only the "Index" is called index.html, so your landing pg is always called index, i.e. your Aboutmeindex can just be index.html portfolio pg can just be called portfolio.html
- You have a good setup for your href tags, but try to update them so they point to your specific LinkedIn/FB/IG/Twitter
- You generally don't want to mix inline styling with external style sheets, so your inline-styling rules for your body tag and your span tags can be pulled out into your css file
- On a related note, you can refactor (reduce the amount of code you write) by creating a class for the styling you put in your span tags so you don't repeat the same line of code multiple times (so maybe you define a class "job-title" and "company" for your spans)
- This is incredibly nit-picky, but the active page is in italics on the mock-up (I'm telling you this only because you really did everything else so well and also if you become a web developer, clients will hound you over minutiae like that - I'm sorry in advance - obviously this is your portfolio and should reflect your style preferences, but just for future reference) 

Great job! 💯
