### ISSUE TITLE
Stephanie Willhide - Week 7 (Weather)

### ISSUE THREAD

**Issue by stephaniewillhide** [Adamor/FEWD3.28#70]
Hey Hailey, this is WAY past due, but I'm just submitting so you know it's complete.

https://github.com/stephaniewillhide/FEWD328_stephanie/commit/04030393355f10b6907832b68c934da5e97c4ee7

Complete: 5
Comfort: 2

Wins: Finally working! I am excited about this, and now I can use APIs in other ways.
Challenges: Working with JavaScript has been challenging, and it's taking me a bit to figure things out.

**Comment by heyyy-sebastian** [comment]
🎊 this is great! You can also use an ajax call to get data from APIs like we went over in class, but the getJSON method is perf and actually ends up being less code. Good job!

The styling looks good - I might add a method right after preventDefault(); to .remove() any h3 elements on the page because otherwise you end up adding strings to the DOM each time you search for a zip code, but you can also just have a running list of weather conditions, up to you ¯\_(ツ)_/¯
