### ISSUE TITLE
Jihyun Song-Final Project

### ISSUE THREAD

**Issue by Jihyunsong0106** [Adamor/FEWD3.28#72]
https://github.com/Jihyunsam143/FEWD328_jihyun/tree/master/cafe-manna

Here is the link for prototype.
http://design-prod-watchae.s3.amazonaws.com/prototypes/ga-fewd-3-28/cafe-manna/index.html

Thanks,
Jihyun

**Comment by heyyy-sebastian** [comment]
Hi Jihyun -

This is beautifully done! This is a clean and polished site and you should be very proud of the work you've done here and overall in class.

Here's a little bit of feedback I have on your site:
- I think the layout looks great on larger screen-sizes and at the mobile breakpoints you've set in your media queries. I'm looking at the version from the cafe-manna-revised folder, and the layout looks a bit tight on my MacBook air (I'll try to add a few screenshots so you can see, not sure if github supports image attachments), so you may need to add one more media query for medium-small laptop screensizes before it changes to iPad sizing. If I'm not looking at the latest version of the site, then free feel to ignore this bit.
- Your html is clean and set up perfectly, but it looks like you have some inline-styling. Generally it's best practice to have styling set exclusively in the CSS files, though the inline-styling with the animation delays might be attached to some of the plugins you're using? If they're not attached to the animations/js in your vendor folder, then I would try to put them your CSS file for clarity/legibility. I would only use inline-styling if that's the way the plugins specify in their directions, because otherwise it gets a little repetitive.
- For some of your CSS, be careful about declaring a styling rule twice for the same element. For example, at lines 36-37 in your css file, you have both `margin-bottom: 16px;` and `margin: 0 auto;` listed. When these rules are compiled together, only the `margin: 0 auto;` will be recognized because for each element/class/id with a block of styling rules, the second margin rule will override the first. That's true for any style attribute that gets declared twice in a style block. If you set `background-color: blue;` and then `background-color: red;` in the same styling block, the background-color will be set to red. If you need the bottom margin, you can try the shorthand `margin: 0 auto 16px;` because you can write margin/padding rules as `margin: [top] [right and left] [bottom];` 

Overall this is great! You've built something that looks professional an is easy to navigate! 👍 💯 🎉

**Comment by heyyy-sebastian** [comment]
![screen shot 2017-06-24 at 6 32 03 pm](https://user-images.githubusercontent.com/17454012/27512384-f443bb5a-590b-11e7-870e-4b3c9076269a.png)
![screen shot 2017-06-24 at 6 31 54 pm](https://user-images.githubusercontent.com/17454012/27512385-f446352e-590b-11e7-8ac3-0fa6f3b8dbcd.png)

hopefully these images will render...
