### ISSUE TITLE
Luke Degnan / Class 2

### ISSUE THREAD

**Issue by ldegnan** [Adamor/FEWD3.28#8]
https://github.com/ldegnan/FEWD328_LUKE/commit/fd6c75602cccee42e18f1d275213a834f87ea159

Comfort: 4 - It was quite a pain to figure out how to get the lines to break with the same indent in the li's. Figured it out tho. I bet there was a more elegant way to do all of this.

Completeness: 5 - I'm pretty sure it's the same as the examples. There might be some font sizing differences.

Wins/Challenges: The indent and the square were wins. The challenges are mostly making the code as pared down as possible. I think that I have too much code.

**Comment by heyyy-sebastian** [comment]
Hey Luke -

This looks excellent! You've done an amazing job of replicating the mock-up.

A few notes on your code:
- Items like the About Me/Portfolio and FB/IG/Twitter/LinkedIn links will typically be formatted in an unordered list; try googling "display: inline" and see if that helps make formatting easier. This approach is more semantic (you're listing different links/pages) and generally compiles/renders better/more consistently than the HTML character entities you have in your code because elements are more current than the char entities. It also makes your HTML more readable
- When you name a class, you don't need to call it "somethingclass"; since you're already defining it as a class inline, and using the .class notation in your css file, that's just a bit redundant. If you want to have a class name that's longer than one word, it's helpful to separate words with dashes, e.g. class="sub-menu"
- As far as how much code you have, this is actually pretty clean; you could try combining some of your class names and elements so you don't have to repeat a class declaration in each list item (i.e. move the resume1 class to the ul and then use the selector `.resume1 li`) BUT we haven't gone over compound selectors yet, so your intuition is taking you in the right direction here, but you'll learn more on how to refactor this tomorrow

Awesome work! 👍
