### ISSUE TITLE
EMILY PANCHAME - Class 2 (3/30)

### ISSUE THREAD

**Issue by emilybpanch** [Adamor/FEWD3.28#9]
https://github.com/emilybpanch/FEWD328_EMILY/commit/923d90de7c63b8bc5f7104e72ea371c00e7545fb

**Comfort:** 3
**Completeness:** 5 (I hope!)
**Wins:** Linking the two sheets together, figuring out how to change the styling in the same line of text, learning special characters (how to do the "e" with an accent aigu), getting more familiar with different CSS styles.
**Challenges:** Sometimes I'm unsure of how to tag certain elements (would it make more sense to use a div or a class). Also I'm not very confident in wrapping text around an image and adding the proper margin/padding.

**Comment by heyyy-sebastian** [comment]
Hi Emily -

This looks really good! I think you have the basics on HTML/CSS on lock.

A few things about your code/questions:
- When it comes to padding, more is typically better. When I was in the intensive course at GA, my instructor would say, "Pad the shit out of it," which is generally a good rule of thumb. It keeps things from looking overcrowded. You could probably increase the padding on your body and add a margin rule to space out your "aboutme" and "sociallinks" divs
- The font could be a bit larger overall - 16px is usually the default and you can adjust from there
- Naming conventions for classes is usually that you use "camel case" lettering if you want to make it all one word, which looksLikeThis (first word lower case, following words start with a capital letter), or you can put dashes-between-words when you define a class to make it more easily readable (e.g. class="social-links"). But also your class naming itself is good and semantic -- it's descriptive and tells me what info might be in the div 
- When you don't want a href to lead anywhere, just put a hash symbol (#); it'll keep you on the same page if you click it
- You're def not the only person in the class to struggle with image positioning, it's still a source of frustration for me, too. Part of the difficulty here might come from where your image element is on the page. I would try moving it down into div#aboutme and see if you can get the text to flow around the image, since it looks like all those elements belong in the same div from the mock-up. More about floats here: https://css-tricks.com/all-about-floats/
- I would try to avoid using !important as much as possible, it can become incredibly unwieldy as a project grows
- Re: do I use a div or a class? Terminology-wise, an element is a tag, so a div element is wrapped in the <div></div> tag and classes belong to these html tags, but I think I see what you're saying. If you're going to style all the tags of a specific type a certain way, it's easiest just to use the html tag in the CSS file, so if all your h1 elements are going to look the same, just use h1 in the style sheet. Adding a class to that just adds extra code to your html file. If there are variations you want to specify of the same element (like if you want the background color to be different for different divs), then use a class. Figuring out which is better mostly comes with practice.

Okay this probably looks like a lot of feedback, but these are all really small things. Conceptually/practically you're really getting it! 👍

**Comment by emilybpanch** [comment]
Wow, thank you for the incredibly thorough and helpful feedback -- I REALLY
appreciate it!! I'll let you know if I have any follow-up questions after I
digest this a little more. See you tonight.
